import type { Metadata } from "next";
import { Inter } from "next/font/google";
import SolanaProvider from "./components/SolanaProvider";
import Script from "next/script";

require("@solana/wallet-adapter-react-ui/styles.css");
require("./globals.css");

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <SolanaProvider>{children}</SolanaProvider>
      </body>
      <Script src="https://telegram.org/js/telegram-web-app.js" strategy="beforeInteractive" />
    </html>
  );
}
